/**
 * Plain-Node mirror of generate-exports.ts. Keep them in sync - the .ts
 * version is the canonical source. This exists only so the script can
 * run on hosts that don't have a working tsx/esbuild for this platform.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, "..");
const REPO_ROOT = path.resolve(PKG_ROOT, "..");
const SRC = path.join(PKG_ROOT, "src");

const ICONS_DIRS = {
	lucide: path.join(REPO_ROOT, "icons", "lucide"),
	huge: path.join(REPO_ROOT, "icons", "huge"),
};

const HEADER = [
	"// AUTO-GENERATED by `pnpm gen`. Do not edit by hand.",
	"// Source of truth: ../../icons/<library>/*-icon.tsx",
	"// Re-exports follow whatever names each icon file actually exports -",
	"// see NAMING_REPORT.md for files where component and handle names",
	"// don't follow the `XxxIcon` / `XxxIconHandle` convention.",
	"",
].join("\n");

const COMPONENT_RE = /(?:const|function)\s+([A-Z][A-Za-z0-9]*Icon)\s*[=(:<]/m;
const HANDLE_RE = /^export\s+(?:interface|type)\s+([A-Z][A-Za-z0-9]*Handle)\b/m;

const parseIcon = async (dir, file) => {
	const stem = file.replace(/-icon\.tsx$/, "");
	const source = await fs.readFile(path.join(dir, file), "utf8");
	const componentMatch = source.match(COMPONENT_RE);
	const handleMatch = source.match(HANDLE_RE);
	return {
		file,
		stem,
		componentName: componentMatch?.[1] ?? null,
		handleName: handleMatch?.[1] ?? null,
	};
};

const isCanonical = (icon) => {
	if (!icon.componentName || !icon.handleName) return false;
	return icon.handleName === `${icon.componentName}Handle`;
};

const buildBarrel = (library, icons) => {
	const lines = [];
	for (const icon of icons) {
		if (!icon.componentName) {
			lines.push(`// SKIP ${icon.file} - no component export found`);
			continue;
		}
		const importPath = `../../icons/${library}/${icon.stem}-icon`;
		lines.push(`export { ${icon.componentName} } from "${importPath}";`);
		if (icon.handleName) {
			lines.push(`export type { ${icon.handleName} } from "${importPath}";`);
		}
		lines.push("");
	}
	return `${HEADER}${lines.join("\n")}`;
};

const buildIndex = (counts) =>
	[
		HEADER,
		"// Top-level entry - types-only.",
		"// Lucide and Huge libraries share several icon names",
		"// (HeartIcon, CopyIcon, etc.), so per-icon imports must come",
		"// from the scoped subpath:",
		"//",
		'//   import { BellRingIcon } from "@animateicons/react/lucide";',
		'//   import { HeartIcon }   from "@animateicons/react/huge";',
		"",
		`// Lucide: ${counts.lucide} icons. Huge: ${counts.huge} icons.`,
		"",
		'export type { IconHandle } from "./lib/icon-handle";',
		"",
	].join("\n");

const buildNamingReport = (parsed) => {
	const sections = [
		"# Naming report",
		"",
		"Icons whose `forwardRef` component name and handle interface name",
		"don't match the canonical `XxxIcon` / `XxxIconHandle` pattern.",
		"",
		"The npm package re-exports them under whatever name each file actually",
		"defines, so they work - but consumers will see inconsistent typing",
		"between, e.g., `BellRingIcon` (paired with `BellRingIconHandle`) and",
		"`BlendIcon` (paired with `BlendHandle`).",
		"",
		"Worth a follow-up pass to rename in-place.",
		"",
	];

	for (const lib of Object.keys(parsed)) {
		const issues = parsed[lib].filter((i) => !isCanonical(i));
		if (!issues.length) continue;

		sections.push(`## ${lib} (${issues.length})`);
		sections.push("");
		sections.push("| File | Component | Handle | Issue |");
		sections.push("| --- | --- | --- | --- |");
		for (const icon of issues) {
			let issue = "";
			if (!icon.componentName) issue = "no component export";
			else if (!icon.handleName) issue = "no handle export";
			else if (
				!icon.handleName.startsWith(icon.componentName.replace(/Icon$/, ""))
			)
				issue =
					"**handle name unrelated to component (probably a copy-paste bug)**";
			else issue = "handle missing `Icon` infix";

			sections.push(
				`| \`${icon.file}\` | ${icon.componentName ?? "-"} | ${icon.handleName ?? "-"} | ${issue} |`,
			);
		}
		sections.push("");
	}

	return sections.join("\n");
};

const main = async () => {
	const parsed = { lucide: [], huge: [] };
	const counts = { lucide: 0, huge: 0 };

	for (const lib of Object.keys(ICONS_DIRS)) {
		const dir = ICONS_DIRS[lib];
		const files = (await fs.readdir(dir))
			.filter((f) => f.endsWith("-icon.tsx"))
			.sort();
		const icons = await Promise.all(files.map((f) => parseIcon(dir, f)));
		parsed[lib] = icons;
		counts[lib] = icons.filter((i) => i.componentName).length;

		await fs.writeFile(
			path.join(SRC, `${lib}.ts`),
			buildBarrel(lib, icons),
			"utf8",
		);
		const skipped = icons.length - counts[lib];
		console.log(
			`  ${lib}: ${counts[lib]} icons -> src/${lib}.ts${skipped ? `  (skipped ${skipped})` : ""}`,
		);
	}

	await fs.writeFile(path.join(SRC, "index.ts"), buildIndex(counts), "utf8");
	console.log(`  index -> src/index.ts`);

	await fs.writeFile(
		path.join(PKG_ROOT, "NAMING_REPORT.md"),
		buildNamingReport(parsed),
		"utf8",
	);
	const issueCount =
		parsed.lucide.filter((i) => !isCanonical(i)).length +
		parsed.huge.filter((i) => !isCanonical(i)).length;
	console.log(`  ${issueCount} naming inconsistencies -> NAMING_REPORT.md`);
	console.log(`Total: ${counts.lucide + counts.huge} icons.`);
};

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
