import type { ShaderGradientSettings } from "@/types/shader-gradient";

// Example presets
export const ExampleGradients: Array<{
	id: string;
	name: string;
	settings: ShaderGradientSettings;
}> = [
	{
		id: "shadergradient-custom",
		name: "Custom Shader Gradient",
		settings: {
			animate: "on",
			type: "sphere",
			wireframe: false,
			shader: "defaults",
			uTime: 0,
			uSpeed: 0.3,
			uStrength: 0.3,
			uDensity: 0.8,
			uFrequency: 5.5,
			uAmplitude: 3.2,
			positionX: -0.1,
			positionY: 0,
			positionZ: 0,
			rotationX: 0,
			rotationY: 130,
			rotationZ: 70,
			color1: "#92dbe0",
			color2: "#0b7bff",
			color3: "#3865cf",
			reflection: 0.4,

			cAzimuthAngle: 270,
			cPolarAngle: 180,
			cDistance: 0.5,
			cameraZoom: 15.1,
			fov: undefined,

			lightType: "env",
			brightness: 0.8,
			envPreset: "city",
			grain: "on",

			pixelDensity: 1,
			pointerEvents: "auto",

			toggleAxis: false,
			zoomOut: false,
			hoverState: "",
			fovEnabled: false,
			enableTransition: false,
		},
	},

	{
		id: "example1",
		name: "Blue Ocean",
		settings: {
			animate: "on",
			type: "waterPlane",
			wireframe: false,
			shader: "defaults",
			uTime: 8,
			uSpeed: 0.3,
			uStrength: 1.5,
			uDensity: 1.5,
			uFrequency: 0,
			uAmplitude: 0,
			positionX: 0,
			positionY: 0,
			positionZ: 0,
			rotationX: 50,
			rotationY: 0,
			rotationZ: -60,
			color1: "#242880",
			color2: "#8d7dca",
			color3: "#212121",
			reflection: 0.1,
			cAzimuthAngle: 180,
			cPolarAngle: 80,
			cDistance: 2.8,
			cameraZoom: 9.1,
			lightType: "3d",
			brightness: 1,
			envPreset: "city",
			grain: "on",
			toggleAxis: false,
			zoomOut: false,
			pixelDensity: 1,
			pointerEvents: "none",
			fovEnabled: false,
		},
	},
	{
		id: "example2",
		name: "Sunset Glow",
		settings: {
			animate: "on",
			type: "plane",
			wireframe: false,
			shader: "defaults",
			uTime: 5,
			uSpeed: 0.2,
			uStrength: 1.2,
			uDensity: 1.0,
			uFrequency: 0,
			uAmplitude: 0,
			positionX: 0,
			positionY: 0,
			positionZ: 0,
			rotationX: 45,
			rotationY: 0,
			rotationZ: 0,
			color1: "#ff7e5f",
			color2: "#feb47b",
			color3: "#ffcda5",
			reflection: 0.2,
			cAzimuthAngle: 180,
			cPolarAngle: 75,
			cDistance: 3.0,
			cameraZoom: 8.0,
			lightType: "3d",
			brightness: 1.2,
			envPreset: "dawn",
			grain: "on",
			toggleAxis: false,
			zoomOut: false,
			pixelDensity: 1,
			fovEnabled: false,
			pointerEvents: "none",
		},
	},
	{
		id: "example3",
		name: "Cosmic Sphere",

		settings: {
			animate: "on",
			type: "waterPlane", // updated from "sphere"
			wireframe: false,
			shader: "positionMix",
			uTime: 10,
			uSpeed: 0.4,
			uStrength: 2,
			uDensity: 2,
			uFrequency: 0,
			uAmplitude: 0,
			positionX: 0,
			positionY: 0,
			positionZ: 0,
			rotationX: 2,
			rotationY: 21,
			rotationZ: 0,
			color1: "#040927",
			color2: "#c22938",
			color3: "#e16f23",
			reflection: 0.3,
			cAzimuthAngle: 180,
			cPolarAngle: 90,
			cDistance: 3.5,
			cameraZoom: 7,
			lightType: "env",
			brightness: 1.1,
			envPreset: "lobby",
			grain: "on",
			toggleAxis: false,
			zoomOut: false,
			hoverState: "",
			enableTransition: false,
			pixelDensity: 1,
			fovEnabled: false,

			pointerEvents: "none",
		},
	},
	{
		id: "example4",
		name: "Neon Wireframe",
		settings: {
			animate: "on",
			type: "waterPlane",
			wireframe: true,
			shader: "defaults",
			uTime: 12,
			uSpeed: 0.5,
			uStrength: 2.5,
			uDensity: 2.0,
			uFrequency: 0,
			uAmplitude: 0,
			positionX: 0,
			positionY: 0,
			positionZ: 0,
			rotationX: 60,
			rotationY: 0,
			rotationZ: 30,
			color1: "#ff00cc",
			color2: "#333399",
			color3: "#00ffff",
			reflection: 0.4,
			cAzimuthAngle: 180,
			cPolarAngle: 70,
			cDistance: 3.2,
			cameraZoom: 8.5,
			lightType: "3d",
			brightness: 1.3,
			envPreset: "city",
			grain: "off",
			toggleAxis: false,
			zoomOut: false,
			pixelDensity: 1,
			fovEnabled: false,
			pointerEvents: "none",
		},
	},
	{
		id: "example5",
		name: "Neon Wireframe",
		settings: {
			animate: "on",
			type: "plane",
			wireframe: true,
			shader: "defaults",
			uTime: 12,
			uSpeed: 0.5,
			uStrength: 2.5,
			uDensity: 2,
			uFrequency: 0,
			uAmplitude: 0,
			positionX: 0,
			positionY: 0,
			positionZ: 0,
			rotationX: 60,
			rotationY: 0,
			rotationZ: 30,
			color1: "#ff00cc",
			color2: "#333399",
			color3: "#00ffff",
			reflection: 0.4,
			cAzimuthAngle: 180,
			cPolarAngle: 70,
			cDistance: 2.6,
			cameraZoom: 8.5,
			lightType: "3d",
			brightness: 1.3,
			envPreset: "city",
			grain: "on",
			toggleAxis: false,
			zoomOut: false,
			hoverState: "",
			fovEnabled: false,
			enableTransition: false,
			pixelDensity: 1,
			pointerEvents: "none",
		},
	},
	{
		id: "example6",
		name: "Neon Wireframe",
		settings: {
			animate: "on",
			type: "plane",
			wireframe: true,
			shader: "positionMix",
			uTime: 12,
			uSpeed: 0.28,
			uStrength: 2.5,
			uDensity: 2,
			uFrequency: 0,
			uAmplitude: 0,
			positionX: 0.7,
			positionY: 0,
			positionZ: 0,
			rotationX: 60,
			rotationY: 0,
			rotationZ: 30,
			color1: "#094a52",
			color2: "#1f1fb3",
			color3: "#009cff",
			reflection: 0.4,
			cAzimuthAngle: 184,
			cPolarAngle: 67,
			cDistance: 3,
			cameraZoom: 8.5,
			lightType: "3d",
			brightness: 1.3,
			envPreset: "city",
			grain: "on",
			toggleAxis: false,
			zoomOut: false,
			hoverState: "",
			fovEnabled: false,
			enableTransition: false,
			pixelDensity: 1,
			pointerEvents: "none",
		},
	},
	{
		id: "example7",
		name: "Purple Galaxy",
		settings: {
			animate: "on",
			type: "sphere",
			wireframe: false,
			shader: "defaults",
			uTime: 0,
			uSpeed: 0.3,
			uStrength: 0.4,
			uDensity: 0.8,
			uFrequency: 5.5,
			uAmplitude: 7,
			positionX: 0,
			positionY: 0,
			positionZ: 0,
			rotationX: 0,
			rotationY: 0,
			rotationZ: 140,
			color1: "#809bd6",
			color2: "#910aff",
			color3: "#af38ff",
			reflection: 0.5,
			cAzimuthAngle: 250,
			cPolarAngle: 140,
			cDistance: 1.5,
			cameraZoom: 12.5,
			lightType: "3d",
			brightness: 1.5,
			envPreset: "city",
			grain: "on",
			toggleAxis: false,
			zoomOut: false,
			hoverState: "",
			fovEnabled: false,
			enableTransition: false,
			pixelDensity: 1,
			pointerEvents: "none",
		},
	},
	{
		id: "example8",
		name: "Aqua Mist",
		settings: {
			animate: "on",
			type: "waterPlane",
			wireframe: false,
			shader: "defaults",
			uTime: 0,
			uSpeed: 0.2,
			uStrength: 3.4,
			uDensity: 1.2,
			uFrequency: 0,
			uAmplitude: 0,
			positionX: 0,
			positionY: 0.9,
			positionZ: -0.3,
			rotationX: 45,
			rotationY: 0,
			rotationZ: 0,
			color1: "#94ffd1",
			color2: "#6bf5ff",
			color3: "#ffffff",
			reflection: 0.1,
			cAzimuthAngle: 170,
			cPolarAngle: 70,
			cDistance: 4.4,
			cameraZoom: 1,
			lightType: "3d",
			brightness: 1.2,
			envPreset: "city",
			grain: "off",
			toggleAxis: false,
			zoomOut: false,
			hoverState: "",
			fovEnabled: false,
			enableTransition: false,
			pixelDensity: 1,
			pointerEvents: "none",
		},
	},
	{
		id: "example9",
		name: "Sunset Sphere",
		settings: {
			animate: "on",
			type: "sphere",
			wireframe: false,
			shader: "defaults",
			uTime: 0,
			uSpeed: 0.3,
			uStrength: 0.3,
			uDensity: 0.8,
			uFrequency: 5.5,
			uAmplitude: 3.2,
			positionX: -0.1,
			positionY: 0,
			positionZ: 0,
			rotationX: 0,
			rotationY: 130,
			rotationZ: 70,
			color1: "#73bfc4",
			color2: "#ff810a",
			color3: "#8da0ce",
			reflection: 0.4,
			cAzimuthAngle: 270,
			cPolarAngle: 180,
			cDistance: 0.5,
			cameraZoom: 15.1,
			lightType: "env",
			brightness: 0.8,
			envPreset: "city",
			grain: "on",
			toggleAxis: false,
			zoomOut: false,
			hoverState: "",
			fovEnabled: false,
			enableTransition: false,
			pixelDensity: 1,
			pointerEvents: "none",
		},
	},
	{
		id: "shadergradient-02",
		name: "City Sphere 3D Gradient",

		settings: {
			animate: "on",
			brightness: 1.1,
			cAzimuthAngle: 0,
			cDistance: 7.1,
			cPolarAngle: 140,
			cameraZoom: 17.3,
			color1: "#000000",
			color2: "#eca811",
			color3: "#ff0808",
			envPreset: "city",
			fov: 45,
			grain: "off",
			lightType: "3d",
			pixelDensity: 1,
			positionX: 0,
			positionY: 0,
			positionZ: 0,
			reflection: 0.1,
			rotationX: 0,
			rotationY: 0,
			rotationZ: 0,
			shader: "defaults",
			type: "sphere",
			uAmplitude: 1.4,
			uDensity: 1.1,
			uFrequency: 5.5,
			uSpeed: 0.1,
			uStrength: 1,
			uTime: 0,
			wireframe: false,

			// Additional required props
			fovEnabled: false,
			enableTransition: false,
			pointerEvents: "none",
		},
	},
	{
		id: "shadergradient-03",
		name: "City WaterPlane Gradient",

		settings: {
			animate: "on",
			brightness: 1.1,
			cAzimuthAngle: 180,
			cDistance: 3.9,
			cPolarAngle: 115,
			cameraZoom: 1,
			color1: "#5606FF",
			color2: "#e63535",
			color3: "#000000",
			envPreset: "city",
			fov: 45,
			grain: "off",
			lightType: "3d",
			pixelDensity: 1,
			positionX: -0.5,
			positionY: 0.1,
			positionZ: 0,
			reflection: 0.1,
			rotationX: 0,
			rotationY: 0,
			rotationZ: 235,
			shader: "defaults",
			type: "waterPlane",
			uAmplitude: 0,
			uDensity: 1.1,
			uFrequency: 5.5,
			uSpeed: 0.1,
			uStrength: 2.4,
			uTime: 0.2,
			wireframe: false,

			// Required extras
			fovEnabled: false,
			enableTransition: false,
			pointerEvents: "none",
		},
	},
	{
		id: "shadergradient-04",
		name: "Dawn Spherical Gradient",

		settings: {
			animate: "on",

			brightness: 1.5,
			cAzimuthAngle: 60,
			cDistance: 7.1,
			cPolarAngle: 90,
			cameraZoom: 15.3,
			color1: "#ff7a33",
			color2: "#33a0ff",
			color3: "#ffc53d",
			envPreset: "dawn",
			fov: 45,
			grain: "off",
			lightType: "3d",
			pixelDensity: 1,
			positionX: 0,
			positionY: -0.15,
			positionZ: 0,
			reflection: 0.1,
			rotationX: 0,
			rotationY: 0,
			rotationZ: 0,
			shader: "defaults",
			type: "sphere",
			uAmplitude: 1.4,
			uDensity: 1.1,
			uFrequency: 5.5,
			uSpeed: 0.1,
			uStrength: 0.4,
			uTime: 0,
			wireframe: false,

			// Required extras
			fovEnabled: false,
			enableTransition: false,
			pointerEvents: "none",
		},
	},
	{
		id: "shadergradient-05",
		name: "Molten WaterPlane",

		settings: {
			animate: "on",
			brightness: 1.2,
			cAzimuthAngle: 180,
			cDistance: 2.4,
			cPolarAngle: 95,
			cameraZoom: 1,
			color1: "#ff6a1a",
			color2: "#c73c00",
			color3: "#FD4912",
			envPreset: "city",
			fov: 45,
			grain: "off",
			lightType: "3d",
			pixelDensity: 1,
			positionX: 0,
			positionY: -2.1,
			positionZ: 0,
			reflection: 0.1,
			rotationX: 0,
			rotationY: 0,
			rotationZ: 225,
			shader: "defaults",
			type: "waterPlane",
			uAmplitude: 0,
			uDensity: 1.8,
			uFrequency: 5.5,
			uSpeed: 0.2,
			uStrength: 3,
			uTime: 0.2,
			wireframe: false,

			// Required extras
			fovEnabled: false,
			enableTransition: false,
			pointerEvents: "none",
		},
	},
];
