packages:
  - "open-sse"
  - "packages/dx-serializer"
  - "packages/dx-cli"
allowBuilds:
  "@parcel/watcher": true
  '@playwright/browser-chromium': false
  "@swc/core": true
  better-sqlite3: true
  bun: false
  core-js: true
  esbuild: true
  keytar: true
  koffi: true
  libxmljs2: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  tls-client-node: true
  unrs-resolver: true
onlyBuiltDependencies: '["@playwright/browser-chromium","bun"]'
